export const WS_CONNECTION_START: "WS_CONNECTION_START" = "WS_CONNECTION_START";
export const WS_CONNECTION_SUCCESS: "WS_CONNECTION_SUCCESS" =
  "WS_CONNECTION_SUCCESS";
export const WS_CONNECTION_ERROR: "WS_CONNECTION_ERROR" = "WS_CONNECTION_ERROR";
export const WS_CONNECTION_CLOSED: "WS_CONNECTION_CLOSED" =
  "WS_CONNECTION_CLOSED";
export const WS_GET_MESSAGE: "WS_GET_MESSAGE" = "WS_GET_MESSAGE";
export const WS_SEND_MESSAGE: "WS_SEND_MESSAGE" = "WS_SEND_MESSAGE";

export const WS_CONNECTION_START_ALL: "WS_CONNECTION_START_ALL" =
  "WS_CONNECTION_START_ALL";
export const WS_CONNECTION_SUCCESS_ALL: "WS_CONNECTION_SUCCESS_ALL" =
  "WS_CONNECTION_SUCCESS_ALL";
export const WS_CONNECTION_ERROR_ALL: "WS_CONNECTION_ERROR_ALL" =
  "WS_CONNECTION_ERROR_ALL";
export const WS_CONNECTION_CLOSED_ALL: "WS_CONNECTION_CLOSED_ALL" =
  "WS_CONNECTION_CLOSED_ALL";
export const WS_GET_MESSAGE_ALL: "WS_GET_MESSAGE_ALL" = "WS_GET_MESSAGE_ALL";
export const WS_SEND_MESSAGE_ALL: "WS_SEND_MESSAGE_ALL" = "WS_SEND_MESSAGE_ALL";
